### ISSUE TITLE
Why is it downloading the blockchain?

### ISSUE THREAD

**Issue by billbeans** [retoaccess1/haveno-reto#7]
I used the linux binary once last night, and then when I opened it today, it says it's "Synchronizing with Monero Mainnet (localhost) at block: [block number]" for hours now. My data file in ~/.bitmonero is at about 60GB so far. What is happening, exactly? I assume it's downloading the entire blockchain? Why would it do this? I don't have a ton of space on this device but I've been clearing stuff out to make room as it syncs.

**Comment by billbeans** [comment]
Now it got stuck at 97% for so long so I restarted it, and I'm back at 1%. I thought it would pick up where it left off

**Comment by retoaccess1** [comment]
This happens when the client detects Monero blockchain files on the machine. By default it should connect to a remote node. 

You can also start Haveno with the argument " --xmrNode=http://xmr-node-eu.cakewallet.com:18081" to launch with a remote node. Once launched, you can configure in the settings how Haveno should behave in the future.
