### ISSUE TITLE
No Seed Nodes Available

### ISSUE THREAD

**Issue by Eclypticon** [retoaccess1/haveno-reto#8]
I'm having this issue on Win 10 and Debian on boot up. Without the nodes, there is nothing.

**Comment by retoaccess1** [comment]
Due to an ongoing ddos attack, it can take a while before you get into the network. Please leave the client open for a few minutes. You should eventually get through. If you can't see many offers after boot, you will slowly receive them from peers with time. This can take up to 30-45 minutes. Once tor pow is properly figured out, this should not happen again.
